// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: notification_proto/notification.proto

package notification_proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TransferStatusCode int32

const (
	TransferStatusCode_Unknown   TransferStatusCode = 0
	TransferStatusCode_Completed TransferStatusCode = 1
	TransferStatusCode_Pending   TransferStatusCode = 2
	TransferStatusCode_Failed    TransferStatusCode = 3
)

// Enum value maps for TransferStatusCode.
var (
	TransferStatusCode_name = map[int32]string{
		0: "Unknown",
		1: "Completed",
		2: "Pending",
		3: "Failed",
	}
	TransferStatusCode_value = map[string]int32{
		"Unknown":   0,
		"Completed": 1,
		"Pending":   2,
		"Failed":    3,
	}
)

func (x TransferStatusCode) Enum() *TransferStatusCode {
	p := new(TransferStatusCode)
	*p = x
	return p
}

func (x TransferStatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransferStatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_proto_notification_proto_enumTypes[0].Descriptor()
}

func (TransferStatusCode) Type() protoreflect.EnumType {
	return &file_notification_proto_notification_proto_enumTypes[0]
}

func (x TransferStatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransferStatusCode.Descriptor instead.
func (TransferStatusCode) EnumDescriptor() ([]byte, []int) {
	return file_notification_proto_notification_proto_rawDescGZIP(), []int{0}
}

// ClientDetail message
type ClientDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *ClientDetail) Reset() {
	*x = ClientDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notification_proto_notification_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDetail) ProtoMessage() {}

func (x *ClientDetail) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_notification_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDetail.ProtoReflect.Descriptor instead.
func (*ClientDetail) Descriptor() ([]byte, []int) {
	return file_notification_proto_notification_proto_rawDescGZIP(), []int{0}
}

func (x *ClientDetail) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type Chunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content []byte             `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	Status  TransferStatusCode `protobuf:"varint,2,opt,name=Status,proto3,enum=notification_proto.TransferStatusCode" json:"Status,omitempty"`
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notification_proto_notification_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_notification_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_notification_proto_notification_proto_rawDescGZIP(), []int{1}
}

func (x *Chunk) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Chunk) GetStatus() TransferStatusCode {
	if x != nil {
		return x.Status
	}
	return TransferStatusCode_Unknown
}

var File_notification_proto_notification_proto protoreflect.FileDescriptor

var file_notification_proto_notification_proto_rawDesc = []byte{
	0x0a, 0x25, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1e, 0x0a, 0x0c, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x61, 0x0a, 0x05, 0x43,
	0x68, 0x75, 0x6e, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x3e,
	0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26,
	0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2a, 0x49,
	0x0a, 0x12, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10,
	0x00, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x10, 0x01,
	0x12, 0x0b, 0x0a, 0x07, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x10, 0x02, 0x12, 0x0a, 0x0a,
	0x06, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x10, 0x03, 0x32, 0x62, 0x0a, 0x0c, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x52, 0x0a, 0x0f, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x54, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x20, 0x2e, 0x6e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x1a, 0x19,
	0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x22, 0x00, 0x30, 0x01, 0x42, 0x49, 0x0a,
	0x12, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x42, 0x11, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x1e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2d, 0x70, 0x75, 0x73, 0x68, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_notification_proto_notification_proto_rawDescOnce sync.Once
	file_notification_proto_notification_proto_rawDescData = file_notification_proto_notification_proto_rawDesc
)

func file_notification_proto_notification_proto_rawDescGZIP() []byte {
	file_notification_proto_notification_proto_rawDescOnce.Do(func() {
		file_notification_proto_notification_proto_rawDescData = protoimpl.X.CompressGZIP(file_notification_proto_notification_proto_rawDescData)
	})
	return file_notification_proto_notification_proto_rawDescData
}

var file_notification_proto_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_notification_proto_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_notification_proto_notification_proto_goTypes = []interface{}{
	(TransferStatusCode)(0), // 0: notification_proto.TransferStatusCode
	(*ClientDetail)(nil),    // 1: notification_proto.ClientDetail
	(*Chunk)(nil),           // 2: notification_proto.Chunk
}
var file_notification_proto_notification_proto_depIdxs = []int32{
	0, // 0: notification_proto.Chunk.Status:type_name -> notification_proto.TransferStatusCode
	1, // 1: notification_proto.Notification.ConnectToServer:input_type -> notification_proto.ClientDetail
	2, // 2: notification_proto.Notification.ConnectToServer:output_type -> notification_proto.Chunk
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_notification_proto_notification_proto_init() }
func file_notification_proto_notification_proto_init() {
	if File_notification_proto_notification_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_notification_proto_notification_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notification_proto_notification_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Chunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_notification_proto_notification_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_proto_notification_proto_goTypes,
		DependencyIndexes: file_notification_proto_notification_proto_depIdxs,
		EnumInfos:         file_notification_proto_notification_proto_enumTypes,
		MessageInfos:      file_notification_proto_notification_proto_msgTypes,
	}.Build()
	File_notification_proto_notification_proto = out.File
	file_notification_proto_notification_proto_rawDesc = nil
	file_notification_proto_notification_proto_goTypes = nil
	file_notification_proto_notification_proto_depIdxs = nil
}
